# Generated by Django 2.2.11 on 2020-03-17 10:02

import collections
from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rest_framework_tus', '0003_auto_20170619_0358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='upload_metadata',
            field=jsonfield.fields.JSONField(load_kwargs={'object_pairs_hook': collections.OrderedDict}),
        ),
    ]
