# Generated by Django 3.2.12 on 2022-03-31 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_framework_tus', '0004_auto_20200317_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='upload_length',
            field=models.BigIntegerField(default=0),
        ),
    ]
